### ISSUE TITLE
vs2017新建项目报错

### ISSUE THREAD

**Issue by fimmy** [waynebaby/MVVM-Sidekick#14]
![_20170607220320](https://user-images.githubusercontent.com/10045957/26882565-54cfb9fc-4bcd-11e7-8a45-7942b821d080.png)
win7和win10上都出现同样的问题
请问这个怎么解决？

**Comment by Garfield550** [comment]
你在 NuGet 包管理器里看看有没有这个版本

![tim 20170609115753](https://user-images.githubusercontent.com/3471836/26960572-ead1a152-4d0a-11e7-86c2-aabbca84f5cb.png)

**Comment by zhuzixian** [comment]
@Garfield550 没有啊。

**Comment by fimmy** [comment]
@Garfield550 没有，最新的是1.6.25

![_20170610081831](https://user-images.githubusercontent.com/10045957/26998398-b16283ea-4db5-11e7-907c-d1a2e8fe7dbe.png)

**Comment by Garfield550** [comment]
@fimmy @zhuzixian 
估计是被韦恩叔 Rollback 了
建议给韦恩发 Mail 或者微博 AT.
😄

**Comment by fimmy** [comment]
自己到nuget安装1.6.25版本好了
