### ISSUE TITLE
关于navigation的文档已过时

### ISSUE THREAD

**Issue by lianzhao** [waynebaby/MVVM-Sidekick#3]
[关于navigation的文档](https://github.com/waynebaby/MVVM-Sidekick/blob/master/MVVMSidekick/Documents/2.ViewModels.md#123-navigation)中，还在调用`ShowAndGetViewModel`方法，而该方法实际已经不存在于v 1.4.x中。
另外，关于如何导航，还有两个问题不明确
1. 导航的target view model对象的创建方式，应该通过new来创建还是应该通过ViewModelLocator来创建？
2. 创建出来的targetVm，是否应该手动dispose？
    * 在[这里](https://github.com/waynebaby/MVVM-Sidekick/blob/master/MVVMSidekick/Documents/3.ViewModels_2.md#225-how-to-dispose-a-view-model-after-a-view-is-closed)，它被放入了using block
    * 而在[这里](https://github.com/waynebaby/MVVM-Sidekick/blob/master/MVVMSidekick/Samples_ViewModels/ViewNavigation_Model.cs#L90)，则没有

**Comment by waynebaby** [comment]
1 如果不传引用进去 就会调用  ViewModelLocator   否则可以自己定义创建方式，这里包含了两层意思
A 可以用ViewModelLocator产生的VM 并且做一些修改
B 可以自己new 一个新的 与原来的locator无关的实例
我个人使用的时候一般是用B。  当然也可以使用自己引入的ioc容器


2 target vm  有一个属性叫做dispose when unload  ( bool)   如果为true 就不需要显性的 dispose
当然在 navigate  show()  的前后写using 并不会造成异常。

**Comment by lianzhao** [comment]
明白了，感谢
