### ISSUE TITLE
Bad Frawmework

### ISSUE THREAD

**Issue by clementmarcotte** [waynebaby/MVVM-Sidekick#4]
I use VS Studio Community 2013, I have ,net Framework 4.6, 4.5.2, 4.5.1, 4.5, 4.0, 4.0 client Profiler and Vsix Installer barks I don't have the right Framework. It is surely time to Microsoft lo launch Framework 2000. Why Microsoft launches products for secret Framework ?

**Comment by waynebaby** [comment]
if you want to use this framework please search  mvvm-sidekick on tools->extension manager， and use the vsix.

this repo is build for multi platform use，and need vs2015 rcto fullly access and manage。

发自我的 Windows Phone
________________________________
发件人: Clément Marcotte<mailto:notifications@github.com>
发送时间: ‎2015/‎6/‎14 2:16
收件人: waynebaby/MVVM-Sidekick<mailto:MVVM-Sidekick@noreply.github.com>
主题: [MVVM-Sidekick] Bad Frawmework (#4)

I use VS Studio Community 2013, I have ,net Framework 4.6, 4.5.2, 4.5.1, 4.5, 4.0, 4.0 client Profiler and Vsix Installer barks I don't have the right Framework. It is surely time to Microsoft lo launch Framework 2000. Why Microsoft launches products for secret Framework ?

---
Reply to this email directly or view it on GitHub:
https://github.com/waynebaby/MVVM-Sidekick/issues/4

**Comment by waynebaby** [comment]
If you mean you cannot access this  VSIX on VS 2013 community edtion.  I will check and upload a new vsix  of it is possible.   this visx is born far before VS 2013 C E. that could happen
