### ISSUE TITLE
请问 MVVM-Sidekick 使用哪种授权协议？

### ISSUE THREAD

**Issue by ztmdsbt** [waynebaby/MVVM-Sidekick#5]
你好。
请问 MVVM-Sidekick 使用哪种授权协议？
是否可以在闭源商业软件上使用？

**Comment by waynebaby** [comment]
Ms-pl   随便使用

发自我的 Windows Phone
________________________________
发件人: 闪电金坷垃<mailto:notifications@github.com>
发送时间: ‎2015/‎7/‎11 21:55
收件人: waynebaby/MVVM-Sidekick<mailto:MVVM-Sidekick@noreply.github.com>
主题: [MVVM-Sidekick] 请问 MVVM-Sidekick 使用哪种授权协议？ (#5)

你好。
请问 MVVM-Sidekick 使用哪种授权协议？
是否可以在闭源商业软件上使用？


---
Reply to this email directly or view it on GitHub:
https://github.com/waynebaby/MVVM-Sidekick/issues/5

**Comment by ztmdsbt** [comment]
Thanks!
