### ISSUE TITLE
 Visual Studio 2015 Pro and Windows Universal App?

### ISSUE THREAD

**Issue by dhk-room101** [waynebaby/MVVM-Sidekick#7]
Hi, is your framework ready to be used in Visual Studio 2015 professional with Windows universal  app on Windows 10?

 Thanks!

**Comment by waynebaby** [comment]
hi cos vs tool for vs 2015 is released 3days before ，i am still working on it


i think it will work on that in  aug 5


发自我的 Windows Phone
________________________________
发件人: dhk-room101<mailto:notifications@github.com>
发送时间: ‎2015/‎8/‎1 8:12
收件人: waynebaby/MVVM-Sidekick<mailto:MVVM-Sidekick@noreply.github.com>
主题: [MVVM-Sidekick]  Visual Studio 2015 Pro and Windows Universal App? (#7)

 Hi, is your framework ready to be used in Visual Studio 2015 professional with Windows universal  app on Windows 10?

 Thanks!

---
Reply to this email directly or view it on GitHub:
https://github.com/waynebaby/MVVM-Sidekick/issues/7

**Comment by waynebaby** [comment]
hi cos vs tool for vs 2015 is released 3days before ，i am still working on it


i think it will work on that in  aug 5


发自我的 Windows Phone



发件人:
dhk-room101
发送时间:
‎2015/‎8/‎1 8:12
收件人:
waynebaby/MVVM-Sidekick
主题:
[MVVM-Sidekick]  Visual Studio 2015 Pro and Windows Universal App? (#7)



Hi, is your framework ready to be used in Visual Studio 2015 professional with Windows universal app on Windows 10?
Thanks!
—
Reply to this email directly or 
view it on GitHub.

**Comment by dhk-room101** [comment]
thank you very much for your reply!  no problem, I'll wait, your framework is awesome and I'm a big fan :-)
 I will check back after August 5 
 thanks again!

**Comment by waynebaby** [comment]
https://visualstudiogallery.msdn.microsoft.com/7942d3cb-1339-4ce1-b074-30059d4cb834

try this beta

**Comment by dhk-room101** [comment]
thank you very much! I'll give it a shot!
 I'm assuming you called it a beta  because it's using the pre-released version  1.6, the vsix  itself is fully functional, right?  Do you have an ETA for the full/complete 1.6 version?
 Thanks!

**Comment by waynebaby** [comment]
Actually the prerelease 1.6x just because wpa81 version have dependency to unity prerelease 3.x
All the other platforms’ template are stable version, and you can use it in any product Environments.

**Comment by waynebaby** [comment]
and unity team will release new version in this month  by their nuget contact mail

**Comment by dhk-room101** [comment]
perfect, thank you very much!

**Comment by waynebaby** [comment]
update: Unity finally released
