### ISSUE TITLE
ListenCanExecuteObservable的问题还是我用错了？

### ISSUE THREAD

**Issue by AuroraDysis** [waynebaby/MVVM-Sidekick#8]
![image](https://cloud.githubusercontent.com/assets/13709836/11528942/ba93ddd4-9924-11e5-8427-54798c9e4b59.png)
![image](http://i12.tietuku.com/38f2d614898bcad3.gif)

**Comment by AuroraDysis** [comment]
今天抽空Debug了一下，我猜问题应该是两个问题
一个是ListenToIsUIBusy的问题，都Concat到一起的话先触发False，后出发UIBusy的True
第二个是少了一行
_CurrentCanExecuteObserverValue = canExe;
![image](https://cloud.githubusercontent.com/assets/13709836/11766997/1f07d146-a1d9-11e5-8e30-622c7c3e70d4.png)

**Comment by waynebaby** [comment]
Hi 我真的没看懂这个问题。 原因问题题干的代码  不是我这边代码片段生成的代码 
而且第二张图片看不到

我建议要不要用  markdown 的方式直接粘贴代码  用```csharp 作为染色把你原来的代码再po一次。。。

**Comment by waynebaby** [comment]
另外  如果要listento UI busy 就不要再listen to observable 了。 这是两个不同的订阅 的确会引起冲突。
你可以把两个observable<bool>  通过 and 算出两个都为true 的情况来订阅到command 的canexecute.

**Comment by waynebaby** [comment]
经过线下确认  的确是 在某次删除代码多删除了这一句  多谢

这就修改发版
