### ISSUE TITLE
vm.StageManager.DefaultStage.Show无法等到返回，已确保是从Template新建而且没有重写默认方法

### ISSUE THREAD

**Issue by AuroraDysis** [waynebaby/MVVM-Sidekick#9]
vm.StageManager.DefaultStage.Show无法等到返回，已确保是从Template新建而且没有重写默认方法
FAQ里的这个的确不管用
如果我改变窗口尺寸虽然没有返回值，但是还是有效果的
如果我这样写那就没有任何问题
vm.StageManager.CurrentBindingView.ContentObject = new LoginPage();

测试样例：
MainWindow是仅一个按钮的MVVMWindow
LoginPage是全黑的MVVMPage

这是FAQ中的
###Q:  
 I found I cannot  got return from `await Show ()` /wire `OnBindedViewLoad()` correctly, when I use MVVM-Sidekick.        (by [mohoo-cc])
 >我在使用MVVM-Sidekick 的时候出现    `await Show ()`无法等到返回， 或者  无法正确的在Show后触发   `OnBindedViewLoad()` 方法。

###A: 
 Please *do* use  MVVM-Sidekick View Templates  to create new view, and make sure there where `base.OnNavigatedTo(e);`  in `OnNavigatedTo()` and 'base.OnNavigatedFrom(e);' in   `OnNavigatedFrom()`.
 
测试：
![test1](https://cloud.githubusercontent.com/assets/13709836/11606256/fda9e586-9b55-11e5-912a-4af566270df9.gif)

**Comment by waynebaby** [comment]
1 我看不到你现在用的是不是 frame 如果是frame 类型，frame 的第一个page是无法再返回的，所以应该无法等到show 结束。 这种没有后退离开Page 的确永远等待不到返回。
2  如果用的是 contentcontrol 类型  需要在vm里面做出一些设置 比如 IsDisposingWhenUnloadNeeded 属性是否为true.



 你给的工程详情太少。只有这几个vm代码我不知道mainwindows 里面的代码 所以无法给更多的支持啊

**Comment by waynebaby** [comment]
确认了问题

WPF默认是使用 Window作为View 载体的   如果用Page 需要再MainPage 加入一个Frame
